"""added user_id on coin, added username on user

Revision ID: b2839926fae9
Revises: 8145720ccb61
Create Date: 2026-05-25 21:25:20.613077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2839926fae9'
down_revision: Union[str, Sequence[str], None] = '8145720ccb61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coins', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'coins', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    op.drop_constraint(None, 'coins', type_='foreignkey')
    op.drop_column('coins', 'user_id')
    # ### end Alembic commands ###
